/*
 MurkMUD++ - A Windows compatible, C++ compatible Merc 2.2 Mud.

 \author Jon A. Lambert
 \date 01/02/2007
 \version 1.5
 \remarks
  This source code copyright (C) 2005, 2006, 2007 by Jon A. Lambert
  All rights reserved.

  Use governed by the MurkMUD++ public license found in license.murk++
*/

#if defined(CMD_LIST)
  #define COMMAND(cmd)  { #cmd, cmd },
  #undef CMD_LIST
#elif defined(CMD_DECL)
  #define COMMAND(cmd)  void cmd(std::string argument);
  #undef CMD_DECL
#else
  #error
#endif

COMMAND (do_areas)
COMMAND (do_memory)
COMMAND (do_kill)
COMMAND (do_murde)
COMMAND (do_murder)
COMMAND (do_backstab)
COMMAND (do_flee)
COMMAND (do_rescue)
COMMAND (do_kick)
COMMAND (do_disarm)
COMMAND (do_sla)
COMMAND (do_slay)
COMMAND (do_cast)
COMMAND (do_note)
COMMAND (do_auction)
COMMAND (do_chat)
COMMAND (do_music)
COMMAND (do_question)
COMMAND (do_answer)
COMMAND (do_shout)
COMMAND (do_yell)
COMMAND (do_immtalk)
COMMAND (do_say)
COMMAND (do_tell)
COMMAND (do_reply)
COMMAND (do_emote)
COMMAND (do_bug)
COMMAND (do_idea)
COMMAND (do_typo)
COMMAND (do_rent)
COMMAND (do_qui)
COMMAND (do_quit)
COMMAND (do_save)
COMMAND (do_follow)
COMMAND (do_order)
COMMAND (do_group)
COMMAND (do_split)
COMMAND (do_gtell)
COMMAND (do_look)
COMMAND (do_examine)
COMMAND (do_exits)
COMMAND (do_score)
COMMAND (do_time)
COMMAND (do_weather)
COMMAND (do_help)
COMMAND (do_who)
COMMAND (do_inventory)
COMMAND (do_equipment)
COMMAND (do_compare)
COMMAND (do_credits)
COMMAND (do_where)
COMMAND (do_consider)
COMMAND (do_title)
COMMAND (do_description)
COMMAND (do_report)
COMMAND (do_practice)
COMMAND (do_wimpy)
COMMAND (do_password)
COMMAND (do_socials)
COMMAND (do_commands)
COMMAND (do_channels)
COMMAND (do_config)
COMMAND (do_wizlist)
COMMAND (do_spells)
COMMAND (do_slist)
COMMAND (do_autoexit)
COMMAND (do_autoloot)
COMMAND (do_autosac)
COMMAND (do_blank)
COMMAND (do_brief)
COMMAND (do_combine)
COMMAND (do_pagelen)
COMMAND (do_prompt)
COMMAND (do_auto)
COMMAND (do_north)
COMMAND (do_east)
COMMAND (do_south)
COMMAND (do_west)
COMMAND (do_up)
COMMAND (do_down)
COMMAND (do_open)
COMMAND (do_close)
COMMAND (do_lock)
COMMAND (do_unlock)
COMMAND (do_pick)
COMMAND (do_stand)
COMMAND (do_rest)
COMMAND (do_sleep)
COMMAND (do_wake)
COMMAND (do_sneak)
COMMAND (do_hide)
COMMAND (do_visible)
COMMAND (do_recall)
COMMAND (do_train)
COMMAND (do_get)
COMMAND (do_put)
COMMAND (do_drop)
COMMAND (do_give)
COMMAND (do_fill)
COMMAND (do_drink)
COMMAND (do_eat)
COMMAND (do_wear)
COMMAND (do_remove)
COMMAND (do_sacrifice)
COMMAND (do_quaff)
COMMAND (do_recite)
COMMAND (do_brandish)
COMMAND (do_zap)
COMMAND (do_steal)
COMMAND (do_buy)
COMMAND (do_list)
COMMAND (do_sell)
COMMAND (do_value)
COMMAND (do_wizhelp)
COMMAND (do_bamfin)
COMMAND (do_bamfout)
COMMAND (do_deny)
COMMAND (do_disconnect)
COMMAND (do_pardon)
COMMAND (do_echo)
COMMAND (do_recho)
COMMAND (do_transfer)
COMMAND (do_at)
COMMAND (do_goto)
COMMAND (do_rstat)
COMMAND (do_ostat)
COMMAND (do_mstat)
COMMAND (do_mfind)
COMMAND (do_ofind)
COMMAND (do_mwhere)
COMMAND (do_hotboo)
COMMAND (do_hotboot)
COMMAND (do_shutdow)
COMMAND (do_shutdown)
COMMAND (do_switch)
COMMAND (do_return)
COMMAND (do_mload)
COMMAND (do_oload)
COMMAND (do_purge)
COMMAND (do_advance)
COMMAND (do_trust)
COMMAND (do_restore)
COMMAND (do_freeze)
COMMAND (do_noemote)
COMMAND (do_notell)
COMMAND (do_silence)
COMMAND (do_peace)
COMMAND (do_ban)
COMMAND (do_allow)
COMMAND (do_wizlock)
COMMAND (do_slookup)
COMMAND (do_sset)
COMMAND (do_mset)
COMMAND (do_oset)
COMMAND (do_rset)
COMMAND (do_users)
COMMAND (do_force)
COMMAND (do_holylight)
COMMAND (do_wizify)
COMMAND (do_owhere)
COMMAND (do_gag)

#undef COMMAND
